/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseDialog: (typeof import('./components/dialogs/BaseDialog.vue'))['default']
    ElButton: (typeof import('element-plus/es'))['ElButton']
    ElCol: (typeof import('element-plus/es'))['ElCol']
    ElForm: (typeof import('element-plus/es'))['ElForm']
    ElFormItem: (typeof import('element-plus/es'))['ElFormItem']
    ElIcon: (typeof import('element-plus/es'))['ElIcon']
    ElInput: (typeof import('element-plus/es'))['ElInput']
    ElRow: (typeof import('element-plus/es'))['ElRow']
    IEpHide: (typeof import('~icons/ep/hide'))['default']
    IEpLock: (typeof import('~icons/ep/lock'))['default']
    IEpUnlock: (typeof import('~icons/ep/unlock'))['default']
    IEpUser: (typeof import('~icons/ep/user'))['default']
    IEpView: (typeof import('~icons/ep/view'))['default']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
    SvgIcon: (typeof import('./components/SvgIcon.vue'))['default']
  }
}
